from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="sii_home"),
    path("alumnos/", views.alumnos_list, name="sii_alumnos"),
    path("alumnos/crear/", views.alumno_crear, name="sii_alumno_crear"),
    path("alumnos/editar/", views.alumno_editar, name="sii_alumno_editar"),
    path("cursos/", views.cursos_list, name="sii_cursos"),
    path("cursos/crear/", views.curso_crear, name="sii_curso_crear"),
    path("cursos/editar/", views.curso_editar, name="sii_curso_editar"),
    path("inscripciones/", views.inscripciones_list, name="sii_inscripciones"),
    path("inscripciones/crear/", views.inscripcion_crear, name="sii_inscripcion_crear"),
    path("inscripciones/baja/", views.inscripcion_baja, name="sii_inscripcion_baja"),
    path("inscripciones/reintento/", views.inscripcion_reintento, name="sii_inscripcion_reintento"),
    path("kardex/", views.kardex, name="sii_kardex"),
    path("alumnos/mi-ficha/", views.mi_ficha, name="sii_mi_ficha"),
    path("alumnos/<int:alumno_id>/", views.alumno_ficha, name="sii_alumno_ficha"),
    path("alumnos/<int:alumno_id>/cuenta/", views.alumno_reset_cuenta, name="sii_alumno_reset_cuenta"),
    path("actas/", views.actas_list, name="sii_actas"),
    path("actas/<int:acta_id>/", views.acta_detalle, name="sii_acta_detalle"),
    path("actas/<int:acta_id>/publicar/", views.acta_publicar, name="sii_acta_publicar"),
    path("periodos/cerrar/", views.periodo_cerrar, name="sii_periodo_cerrar"),
    path("horario/", views.horario_list, name="sii_horario"),
    path("horario/crear/", views.horario_crear, name="sii_horario_crear"),
    path("horario/quitar/", views.horario_quitar, name="sii_horario_quitar"),
    path("periodos/", views.periodos_list, name="sii_periodos"),
    path("periodos/crear/", views.periodo_crear, name="sii_periodo_crear"),
    path("periodos/editar/", views.periodo_editar, name="sii_periodo_editar"),
    path("docentes/", views.docentes_list, name="sii_docentes"),
    path("docentes/crear/", views.docente_crear, name="sii_docente_crear"),
    path("docentes/editar/", views.docente_editar, name="sii_docente_editar"),
    path("docentes/asignar/", views.asignacion_crear, name="sii_asignacion_crear"),
    path("docentes/asignacion/quitar/", views.asignacion_quitar, name="sii_asignacion_quitar"),
]
