# Generated by Django 4.2.11 on 2026-09-21 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0002_inscripcion_edicion_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('cerrada', 'Cerrada')], default='borrador', max_length=20)),
                ('publicada_por_id', models.PositiveIntegerField(blank=True, null=True)),
                ('publicada_en', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='sii.curso')),
            ],
            options={
                'db_table': 'tra_acta_final',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HorarioSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(blank=True, default='', max_length=80)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='sii.curso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='sii.periodo')),
            ],
            options={
                'db_table': 'cat_horario_slot',
                'ordering': ['periodo', 'curso', 'dia', 'hora_inicio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActaRenglon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('acreditado', models.BooleanField(default=False)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones', to='sii.actafinal')),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='renglon_acta', to='sii.inscripcion')),
            ],
            options={
                'db_table': 'tra_acta_renglon',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='actafinal',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='sii.periodo'),
        ),
        migrations.AlterUniqueTogether(
            name='actafinal',
            unique_together={('curso', 'periodo')},
        ),
    ]
