# Generated by Django 4.2.11 on 2026-09-20 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=100.0, help_text='Valor máximo de la actividad (ej: 100 puntos)', max_digits=5)),
                ('tipo', models.CharField(choices=[('tarea', 'Tarea'), ('examen', 'Examen'), ('proyecto', 'Proyecto'), ('participacion', 'Participación')], default='tarea', max_length=20)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada')], default='activa', max_length=20)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='sii.curso')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='sii.inscripcion')),
            ],
            options={
                'verbose_name': 'Kardex',
                'verbose_name_plural': 'Kardex',
            },
        ),
        migrations.CreateModel(
            name='CalificacionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, help_text='Calificación obtenida', max_digits=5, null=True)),
                ('fecha_calificacion', models.DateField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='aula.actividad')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_actividades', to='sii.inscripcion')),
            ],
            options={
                'verbose_name': 'Calificación de Actividad',
                'verbose_name_plural': 'Calificaciones de Actividades',
                'unique_together': {('actividad', 'inscripcion')},
            },
        ),
    ]
