# Generated by Django 4.2.11 on 2026-09-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_entrega_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionactividad',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='entregas/%Y/%m/'),
        ),
    ]
