# Generated by Django 4.2.11 on 2026-09-20 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sii', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id_vendedor', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('comision_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'cat_vendedor',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_alumno_sii',
            field=models.ForeignKey(blank=True, db_column='id_alumno_sii', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_venta', to='sii.alumno'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='duracion_horas',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='modalidad',
            field=models.CharField(choices=[('online', 'En línea'), ('presencial', 'Presencial'), ('hibrido', 'Híbrido')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('borrador', 'Borrador')], default='confirmada', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='venta',
            name='registrado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=19)),
                ('metodo', models.CharField(default='transferencia', max_length=20)),
                ('referencia', models.CharField(blank=True, default='', max_length=60)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='aplicado', max_length=20)),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta')),
            ],
            options={
                'db_table': 'tra_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EdicionCurso',
            fields=[
                ('id_edicion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_edicion', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cupo_maximo', models.SmallIntegerField(default=20)),
                ('cupo_ocupado', models.SmallIntegerField(default=0)),
                ('precio_edicion', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('estado', models.CharField(default='programada', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ediciones', to='ventas.producto')),
            ],
            options={
                'db_table': 'cat_edicion_curso',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='id_vendedor',
            field=models.ForeignKey(blank=True, db_column='id_vendedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventas', to='ventas.vendedor'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='id_edicion',
            field=models.ForeignKey(blank=True, db_column='id_edicion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles_venta', to='ventas.edicioncurso'),
        ),
    ]
